spring:
  config:
    import: optional:configserver:http://localhost:8182
  application:
    name: customers
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    allow-redirects: true
    service-url:
      defaultZone: http://localhost:8010/eureka/
    fetch-registry: true
    register-with-eureka: true
