spring:
  security:
    user:
      name: user
      password: 123456
  config:
    import: discovery.yml
  application:
    name: posts
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:${DB_PORT:5432}/microservice
    username: ifzz
    password: ifzz
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
  devtools:
    restart:
      enabled: true
server:
  port: 8020
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    allow-redirects: true
    service-url:
      defaultZone: http://localhost:8010/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  cloudfoundry:
    enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
