spring:
  config:
    import: optional:configserver:http://localhost:8182
  application:
    name: posts
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    # custom instance id
    # instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    allow-redirects: true
    service-url:
      defaultZone: http://localhost:8010/eureka/
    fetch-registry: true
    register-with-eureka: true
