#https://github.com/khezen/compose-postgres
version: '3'

services:

  postgres:
    container_name: microservice
    image: postgres:9.6.23
    build:
      context: .
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - ./init/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./data:/opt/data
    ports:
      - "5434:5432"
    restart: always

volumes:
  postgres-data:
